import React from 'react';
import { Activity, X, Flame, Droplet, Zap, Award } from 'lucide-react';

interface NutritionData {
  calories: number;
  protein: string;
  carbs: string;
  fat: string;
  highlight: string;
}

interface NutritionModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: NutritionData | null;
  isLoading: boolean;
  foodName: string;
}

const NutritionModal: React.FC<NutritionModalProps> = ({ isOpen, onClose, data, isLoading, foodName }) => {
  if (!isOpen) return null;

  return (
    <div className="absolute inset-0 z-30 flex items-end sm:items-center justify-center pointer-events-none">
      <div 
        className="w-full sm:w-[350px] bg-black/80 backdrop-blur-xl border-t sm:border border-white/10 p-6 rounded-t-3xl sm:rounded-3xl shadow-2xl pointer-events-auto transform transition-transform animate-in slide-in-from-bottom duration-300 mb-0 sm:mb-20"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex justify-between items-start mb-6">
          <div>
            <h3 className="text-emerald-400 font-bold tracking-wider text-xs uppercase mb-1">AI Nutrition Facts</h3>
            <h2 className="text-white font-serif text-xl">{foodName}</h2>
          </div>
          <button onClick={onClose} className="p-1 text-neutral-400 hover:text-white rounded-full hover:bg-white/10 transition-colors">
            <X size={20} />
          </button>
        </div>

        {isLoading ? (
          <div className="flex flex-col items-center justify-center py-8 space-y-3">
             <Activity className="text-emerald-500 animate-pulse" size={32} />
             <p className="text-neutral-400 text-sm animate-pulse">Analyzing ingredients...</p>
          </div>
        ) : data ? (
          <div className="space-y-6">
            <div className="grid grid-cols-4 gap-2">
              <div className="bg-white/5 rounded-2xl p-3 flex flex-col items-center border border-white/5">
                <Flame size={16} className="text-orange-500 mb-2" />
                <span className="text-white font-bold text-lg">{data.calories}</span>
                <span className="text-[10px] text-neutral-400 uppercase tracking-wide">Kcal</span>
              </div>
              <div className="bg-white/5 rounded-2xl p-3 flex flex-col items-center border border-white/5">
                <Zap size={16} className="text-blue-500 mb-2" />
                <span className="text-white font-bold text-lg">{data.protein.replace('g', '')}</span>
                <span className="text-[10px] text-neutral-400 uppercase tracking-wide">Prot</span>
              </div>
              <div className="bg-white/5 rounded-2xl p-3 flex flex-col items-center border border-white/5">
                <Award size={16} className="text-yellow-500 mb-2" />
                <span className="text-white font-bold text-lg">{data.carbs.replace('g', '')}</span>
                <span className="text-[10px] text-neutral-400 uppercase tracking-wide">Carb</span>
              </div>
              <div className="bg-white/5 rounded-2xl p-3 flex flex-col items-center border border-white/5">
                <Droplet size={16} className="text-pink-500 mb-2" />
                <span className="text-white font-bold text-lg">{data.fat.replace('g', '')}</span>
                <span className="text-[10px] text-neutral-400 uppercase tracking-wide">Fat</span>
              </div>
            </div>
            
            <div className="bg-emerald-500/10 border border-emerald-500/20 rounded-xl p-4">
              <p className="text-emerald-200 text-sm italic leading-relaxed">
                "{data.highlight}"
              </p>
            </div>
            
            <p className="text-[10px] text-neutral-500 text-center">
              *Estimations generated by AI based on standard ingredients.
            </p>
          </div>
        ) : (
          <div className="text-center py-4 text-neutral-400">
            Could not retrieve data.
          </div>
        )}
      </div>
    </div>
  );
};

export default NutritionModal;